language: java
sudo: required
services: 
  - docker

# before_install: cd api && mvn test
script:
  - docker-compose build #.././build.sh
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-2"
#   app: "Test" #app name is application name in ec2 beanstalk
#   env: "Test-env"
#   bucket_name: "elasticbeanstalk-ap-southeast-2-507725842651"
#   bucket_path: "Test" #app name 
#   skip_cleanup: true
#   on:
#     branch: develop
#   access_key_id: $AWS_ACCESS_KEY
#   secret-access-key: "$AWS_SECRET_KEY"
# after_deploy:
#   script: docker-compose up --scale api=5 --scale nginx-lb=1 -d
after_success: 
  - "echo 'Finish'"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker tag myobops_api:latest dishitd/ops-repo:myobops_api
  - docker push dishitd/myobops_api
  - docker tag myobops_nginx-lb:latest dishitd/ops-repo:myobops_nginx_lb
  - docker push dishitd/myobops_nginx_lb

