version: '3.7'
services:
  api:
      build:
        context: ./
        dockerfile: ./api/Dockerfile
        
  nginx-lb:
      build: ./nginx-lb
      
      links:
          - api
      ports:
          - '8080:8080'
