version: '3.7'
services:
  api1:
      build: ./api
      tty: true
      
  api2:
      build: ./api
      tty: true
      
  api3:
      build: ./api
      tty: true
      
  loadbalancer:
      build: ./nginx-lb
      tty: true
      links:
          - api1
          - api2
          - api3
      ports:
          - '8080:8080'
