version: '3.3'
services:
  api:
      build:
        context: ./
        dockerfile: ./api/Dockerfile
        
  nginx-lb:
      build: ./nginx-lb
      
      links:
          - api
      ports:
          - '80:80'
